[package]
name = "crawler"
version = "0.0.1"
edition = "2021"

[dependencies]
common = { path = "../common" }
clap = { version = "4.0.29", features = ["derive"] }
serde_json = "1.0.89"
kafka = "0.9.0"
openssl-sys = "0.9.77"