[package]
name = "common"
version = "0.0.1"
edition = "2021"

[dependencies]
kafka = "0.9.0"
serde = { version="1.0.148", features=["derive"] }
serde_json = "1.0.89"
log = "0.4.0"
env_logger = "0.10.0"